
package com.console.main;
import com.console.dao.ThongKeDAO;
import com.console.swing.ScrollBar;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import raven.chart.ModelChart;


public class PanelThongKe extends javax.swing.JPanel {

    ThongKeDAO dao = new ThongKeDAO();
    
    public PanelThongKe() {
        initComponents();
        spTable2.setVerticalScrollBar(new ScrollBar());
        spTablle1.setVerticalScrollBar(new ScrollBar());
        spTablle2.setVerticalScrollBar(new ScrollBar());
        chart.setTitle("Biểu đồ theo ngày");
        //chart.addLegend("Month", Color.decode("#e65c00"), Color.decode("#dc2430"));
        chart.addLegend("Doanh thu", Color.decode("#7b4397"), Color.decode("#FFFFFF"));
        //chart.addLegend("Cost", Color.decode("#e65c00"), Color.decode("#F9D423"));
        //chart.addLegend("Profit", Color.decode("#0099F7"), Color.decode("#FFFFFF"));
        
        
        chart1.setTitle("Biểu đồ theo tháng");
        //chart.addLegend("Month", Color.decode("#e65c00"), Color.decode("#dc2430"));
        chart1.addLegend("Doanh thu", Color.decode("#7b4397"), Color.decode("#FFFFFF"));
        //chart.addLegend("Cost", Color.decode("#e65c00"), Color.decode("#F9D423"));
        //chart2.addLegend("Profit", Color.decode("#0099F7"), Color.decode("#FFFFFF"));
        
        setData();
        setData1();
        fillTableTKTN();
        fillTableTKTT();
        fillTableTKNV();
    }
    void fillTableTKTN() {
        DefaultTableModel model = (DefaultTableModel) tblTKTN.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getTKTN();
        for(Object[] row : list){
            model.addRow(row);
        }
    }
    void setData(){
        List<ModelData> list = dao.bieuDo();
           for (int i = list.size() - 1; i >= 0; i--) {
                ModelData d = list.get(i);
                chart.addData(new ModelChart(d.getMonth(), new double[]{d.getAmount(), d.getProfit()}));
           }
            chart.start();
    }
    void setData1(){
        List<ModelData1> list = dao.bieuDoThang();
           for (int i = list.size() - 1; i >= 0; i--) {
                ModelData1 d = list.get(i);
                chart1.addData(new ModelChart(d.getMonth(), new double[]{d.getAmount(), d.getProfit()}));
           }
            chart1.start();
    }
    void fillComboBoxThang(){
        
    }
    void fillTableTKTT() {
        DefaultTableModel model = (DefaultTableModel) tblTKTT.getModel();
        model.setRowCount(0);
        String thang = cbbThang.getSelectedItem().toString();
        List<Object[]> list = dao.getTKTT(thang);
        for(Object[] row : list){
            model.addRow(row);
        }
    }
    void fillTableTKNV() {
        DefaultTableModel model = (DefaultTableModel) tblTKNV.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getTKNV();
        for(Object[] row : list){
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTabbed1 = new com.console.swing.MaterialTabbed();
        jPanel1 = new javax.swing.JPanel();
        spTablle1 = new javax.swing.JScrollPane();
        tblTKTN = new com.console.swing.Table();
        jPanel3 = new javax.swing.JPanel();
        spTablle2 = new javax.swing.JScrollPane();
        tblTKTT = new com.console.swing.Table();
        cbbThang = new com.console.swing.Combobox();
        jPanel2 = new javax.swing.JPanel();
        spTable2 = new javax.swing.JScrollPane();
        tblTKNV = new com.console.swing.Table();
        jPanel4 = new javax.swing.JPanel();
        panelShadow1 = new raven.panel.PanelShadow();
        chart = new raven.chart.CurveLineChart();
        jPanel5 = new javax.swing.JPanel();
        panelShadow2 = new raven.panel.PanelShadow();
        chart1 = new raven.chart.CurveLineChart();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblTKTN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán ra", "Tổng thu", "Thời gian"
            }
        ));
        tblTKTN.setEnabled(false);
        spTablle1.setViewportView(tblTKTN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTablle1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTablle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("TK doanh thu sản phẩm theo ngày", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTKTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán ra", "Tổng thu", "Thời gian"
            }
        ));
        tblTKTT.setEnabled(false);
        spTablle2.setViewportView(tblTKTT);

        jPanel3.add(spTablle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 1005, 400));

        cbbThang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbbThang.setLabeText("Tháng");
        cbbThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbThangMouseClicked(evt);
            }
        });
        cbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangActionPerformed(evt);
            }
        });
        jPanel3.add(cbbThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 175, -1));

        materialTabbed1.addTab("TK doanh thu sản phẩm theo tháng", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblTKNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên nhân viên", "Tên sản phẩm", "Số sp đã bán", "Thời gian"
            }
        ));
        tblTKNV.setEnabled(false);
        spTable2.setViewportView(tblTKNV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable2, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Thống kê doanh thu theo nhân viên", jPanel2);

        panelShadow1.setBackground(new java.awt.Color(0, 102, 102));
        panelShadow1.setColorGradient(new java.awt.Color(0, 102, 153));
        panelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chart.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        chart.setForeground(new java.awt.Color(255, 255, 255));
        panelShadow1.add(chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1000, 432));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        materialTabbed1.addTab("Biểu đồ doanh thu tháng hiện tại", jPanel4);

        panelShadow2.setBackground(new java.awt.Color(0, 102, 102));
        panelShadow2.setColorGradient(new java.awt.Color(0, 102, 153));
        panelShadow2.setPreferredSize(new java.awt.Dimension(1025, 619));
        panelShadow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chart1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        chart1.setForeground(new java.awt.Color(255, 255, 255));
        panelShadow2.add(chart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1000, 432));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        materialTabbed1.addTab("Biểu đồ doanh thu theo tháng", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbThangMouseClicked
        
    }//GEN-LAST:event_cbbThangMouseClicked

    private void cbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangActionPerformed
        fillTableTKTT();
    }//GEN-LAST:event_cbbThangActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.console.swing.Combobox cbbThang;
    private raven.chart.CurveLineChart chart;
    private raven.chart.CurveLineChart chart1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.console.swing.MaterialTabbed materialTabbed1;
    private raven.panel.PanelShadow panelShadow1;
    private raven.panel.PanelShadow panelShadow2;
    private javax.swing.JScrollPane spTable2;
    private javax.swing.JScrollPane spTablle1;
    private javax.swing.JScrollPane spTablle2;
    private com.console.swing.Table tblTKNV;
    private com.console.swing.Table tblTKTN;
    private com.console.swing.Table tblTKTT;
    // End of variables declaration//GEN-END:variables
}
